on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '59 23 * * *'

jobs:
  unittests:
    name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        environment-file: [ci/36-GIT.yaml, ci/36-PYPI.yaml, ci/37-GIT.yaml, ci/37-PYPI.yaml, ci/38-GIT.yaml, ci/38-PYPI.yaml]
        exclude:
           - environment-file: ci/36-PYPI.yaml
             os: windows-latest
           - environment-file: ci/36-GIT.yaml
             os: windows-latest
    defaults:
       run:
         shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(matrix.environment-file) }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          mamba-version: '*'
          channels: conda-forge
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: ${{ matrix.environment-file }}
          activate-environment: test
          use-only-tar-bz2: true
      - run: mamba info --all
      - run: mamba list
      - run: conda config --show-sources
      - run: conda config --show
      - run: cp utils/matplotlibrc .
      - run: python -c 'import libpysal; libpysal.examples.load_example("Guerry"); libpysal.examples.load_example("Rio Grande do Sul")'
      - run: pytest -v splot --cov=splot --cov-config=.coveragerc --cov-report=xml #--doctest-modules
      - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: splot-codecov
 
