name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
      - cron: '59 23 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: Manual Unittest Run
        default: test
        required: false
jobs:
  testing:
    env:
      RUN_TEST: pytest splot -v -r a --cov splot --cov-config .coveragerc --cov-report xml --color yes --cov-append --cov-report term-missing
    name: ${{ matrix.os }}, ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        environment-file:
          - ci/38-MIN.yaml
          - ci/38.yaml
          - ci/39.yaml
          - ci/310.yaml
          - ci/311.yaml
          - ci/311-DEV.yaml
        include:
          - environment-file: ci/311.yaml
            os: macos-latest
          - environment-file: ci/311.yaml
            os: windows-latest
      fail-fast: false

    defaults:
       run:
         shell: bash -l {0}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: 'latest'

      - name: install bleeding edge PySAL submodules (only Ubuntu / Python 3.10)
        run: |
          pip install git+https://github.com/pysal/libpysal.git@main
          pip install git+https://github.com/pysal/mapclassify.git@main
          pip install git+https://github.com/pysal/esda.git@main
          pip install git+https://github.com/pysal/spreg.git@main
          pip install git+https://github.com/pysal/giddy.git@main
        if: matrix.os == 'ubuntu-latest' && contains(matrix.environment-file, 'DEV')

      - name: install libpysal example datasets
        run: |
          python -c 'import libpysal; libpysal.examples.load_example("Guerry"); libpysal.examples.load_example("Rio Grande do Sul")'

      - name: install and import splot
        run: |
          python -m pip install --no-deps -e .
          python -c 'import splot'

      - name: copy matplotlibrc
        run: cp utils/matplotlibrc .

      - name: environment info
        run: |
          micromamba info
          micromamba list
       
      - name: spatial versions
        run: 'python -c "import geopandas; geopandas.show_versions();"'

      - name: run tests
        run: |
          pytest splot -v -r a --cov splot --cov-config .coveragerc --cov-report xml --color yes --cov-append --cov-report term-missing
  
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: splot-codecov

      - name: Generate and publish the report
        if: |
          failure()
          && steps.status.outcome == 'failure'
          && github.event_name == 'schedule'
          && github.repository_owner == 'pysal'
        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: pytest-log.jsonl
